# Generated by Django 2.2.12 on 2020-12-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_quest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='responsed',
            field=models.BooleanField(default=False),
        ),
    ]
