# Generated by Django 2.2.12 on 2021-01-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_quest', '0003_question_quote_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(default='', max_length=420),
        ),
    ]
