# Generated by Django 2.2.12 on 2021-01-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask_quest', '0004_auto_20210105_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='response_text',
            field=models.TextField(default='', max_length=1255),
        ),
    ]
